# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods, IgnoreNotImplementedMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 22
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 69

# Offense count: 4
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 172

# Offense count: 3
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 133

# Offense count: 3
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 17
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 41

# Offense count: 4
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 15

# Offense count: 4
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: at, by, db, id, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - 'app/models/micropost.rb'
    - 'app/models/week_target.rb'

# Offense count: 6
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 13
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'Gemfile'
    - 'app/models/micropost.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SingleLineConditionsOnly, IncludeTernaryExpressions.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/microposts_controller.rb'
    - 'app/controllers/week_targets_controller.rb'
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/DefWithParentheses:
  Exclude:
    - 'app/models/week_target.rb'

# Offense count: 49
Style/Documentation:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/book_categories_controller.rb'
    - 'app/controllers/book_registers_controller.rb'
    - 'app/controllers/books_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: each, for
Style/For:
  EnforcedStyle: each

# Offense count: 120
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 10
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/books_controller.rb'
    - 'app/controllers/microposts_controller.rb'
    - 'app/controllers/week_targets_controller.rb'
    - 'app/models/micropost.rb'
    - 'app/models/user.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Offense count: 8
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/microposts_controller.rb'
    - 'app/models/micropost.rb'
    - 'app/models/user.rb'
    - 'bin/bundle'
    - 'config/application.rb'

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'app/controllers/book_categories_controller.rb'
    - 'app/controllers/book_registers_controller.rb'
    - 'app/controllers/books_controller.rb'
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/microposts_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/week_targets_controller.rb'
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: both, prefix, postfix
Style/NegatedIf:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: MinDigits, Strict.
Style/NumericLiterals:
  Exclude:
    - 'app/controllers/microposts_controller.rb'
    - 'app/controllers/week_targets_controller.rb'
    - 'app/models/micropost.rb'
    - 'app/models/week_target.rb'
    - 'db/schema.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/microposts_controller.rb'
    - 'app/controllers/week_targets_controller.rb'
    - 'app/helpers/microposts_helper.rb'
    - 'app/models/micropost.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantInterpolation:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'app/models/micropost.rb'

# Offense count: 23
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'app/models/micropost.rb'
    - 'app/models/university.rb'
    - 'app/models/user.rb'
    - 'app/models/week_target.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 521
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets

# Offense count: 35
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 281
