# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.7.2
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# 引数の最小文字数3文字以下を2文字以下に変更。加えて以下の配列の文字列を許可。
Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames: ["n"]

# 数字の桁数区切りを６桁まで許可
NumericLiterals:
  MinDigits: 6

# 1行の長さ最大120文字を最大150文字までに変更
Layout/LineLength:
  Max: 150

# クラスの長さ最大100行までを130行までに変更
Metrics/ClassLength:
  Max: 130

# inverse_ofオプションを利用しないことを許可
Rails/InverseOf:
  Enabled: false

# ハッシュにシンボルがあるときはRuby1.9構文の使用を強制
Style/HashSyntax:
  EnforcedStyle: 'ruby19'