# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.7.2
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# 引数の最小文字数3文字(デフォルト)を2文字以下に変更。以下の配列の文字列を例外的に許可。
Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames: ["n"]

# 数字の桁数区切りのチェックを無効
NumericLiterals:
  Enabled: false

# 1行の長さ最大120文字を最大160文字までに変更
Layout/LineLength:
  Max: 160

# クラスの長さ最大100行までを150行までに変更
Metrics/ClassLength:
  Max: 150

# inverse_ofオプションの利用を強制しない。
Rails/InverseOf:
  Enabled: false

# dependentオプションの利用を強制しない。
Rails/HasManyOrHasOneDependent:
  Enabled: false

# ハッシュにシンボルがあるときはRuby1.9構文の使用を強制
Style/HashSyntax:
  EnforcedStyle: 'ruby19'

# メソッドの行数を最大10行から50行に変更
Metrics/MethodLength:
  Max: 50

# メソッドの循環的複雑度を最大7から15に変更
Metrics/CyclomaticComplexity:
  Max: 15

# メソッドの知覚的複雑度を最大7から15に変更
Metrics/PerceivedComplexity: 
  Max: 15

# %i構文を使用した配列をチェックする
Style/SymbolArray:
  EnforcedStyle: brackets

# メソッドの複雑さの基準値15を70に変更
Metrics/AbcSize:
  Max: 70